### ISSUE TITLE
HAL refactor

### ISSUE THREAD

**Issue by egkoppel** [egkoppel/popcorn-2#14]
- [x] Combine HALs into single `kernel_hal` crate with `cfg(target = ...)` modules
This prevents any issues from the orphan rule if we go with something like the paging2 design for the paging HAL
- [x] Move existing amd64 HAL code into a `Hal` trait
- [x] Refactor paging introduced by #11 to be partially split into the new `kernel_hal` crate (see #16)
- [x] Move interrupt control for `kernel_api::sync` into the HAL
- [x] Expose interrupt table through HAL (#18)

Implementation progess:
- #15 
- #30 (interrupt control was part of this for some reason)
