### ISSUE TITLE
Tracking issue for `mmap`

### ISSUE THREAD

**Issue by egkoppel** [egkoppel/popcorn-2#24]
Feature gate: ~~`#![feature(kernel_mmap)]`~~ `#![feature(kernel_mmap_to_parts)]`, `#![feature(kernel_mmap_config)]`, `#![feature(kernel_mmap_trait)]`

This is a tracking issue for an mmap style API for controlling page table mappings.

### Public API

```rust
// kernel_api::memory::mapping

pub struct DiscontiguityError;

pub struct RawMapping<'a, R: Mappable, V: VirtualAllocator> { ... } // stable

impl RawMapping {
    pub fn new(config: Config) -> Result<Self, AllocError>; // stable

    pub fn resize(&mut self, new_size: usize) -> Result<(), AllocError>;
    pub fn resize_in_place(&mut self, new_size: usize) -> Result<(), AllocError>; // stable

    pub fn into_contiguous_raw_parts(self) -> Result<(OwnedFrames, OwnedPages), DiscontiguityError>;
    pub unsafe fn from_contiguous_raw_parts(frames: OwnedFrames, pages: OwnedPages) -> Self;

    // how best to control which allocator without having `clone_into` variants explode
    pub fn clone_into(&self, address_space: AddressSpace, location: Location) -> Self;
}

pub enum Protection {
    Unmapped,
    ReadOnly { executable: bool },
    Writable { executable: bool },
}

pub enum Location<A = Page> {
    Any, // stable
    At(A), // stable
    Near { address: A, alignment: NonZeroUsize },
    Below { address: A, alignment: NonZeroUsize },
}

pub enum Lazy { Lazy, AllocateNow }

pub struct Config<'physical_allocator, V: VirtualAllocator> { ... } // stable

impl Config {
    pub fn new(len: NonZero<usize>) -> Self; // stable

    pub fn physical_allocator(self, allocator: &dyn PhysicalAllocator) -> Self;
    pub fn virtual_allocator(self, allocator: impl VirtualAllocator) -> Self;

    pub fn physical_location(self, location: Location<Frame>) -> Self; // stable
    pub fn virtual_location(self, location: Location<Page>) -> Self;

    pub fn protection(self, protection: Protection) -> Self;
    pub fn laziness(self, laziness: Lazy) -> Self;
}

pub trait Mappable {
    fn physical_length_to_virtual_length(physical_length: NonZero<usize>) -> NonZero<usize>;
    fn physical_start_offset_from_virtual() -> isize;
}

pub enum RawStack {} // Exposition only
pub enum RawMmap {} // Exposition only
impl Mappable for RawStack { ... }
impl Mappable for RawMmap { ... }

pub type Stack<'a, V: VirtualAllocator> = RawMapping<'a, RawStack, V>; // stable
pub type Mapping<'a, V: VirtualAllocator> = RawMapping<'a, RawMmap, V>; // stable
```

### Steps / History

- [ ] Implementation:
    - [x] #30 
    - [x] #52 
    - [x] #124
- [ ] Stabilization PR
    - [x] #126

### Unresolved Questions

- [x] How to control address space of the mapping (https://github.com/popcorn-2/popcorn-2/issues/24#issuecomment-1911021642)
- [x] How to ensure virtual allocator is valid for the address space requested (https://github.com/popcorn-2/popcorn-2/issues/24#issuecomment-1911021642)
- [x] How to force physical/virtual addresses to be at some specific point/within a specific region 
    - Partly controlled by the `BackingAllocator` used, as eg. `dmamem()` would force allocation in the lower 4GiB of physical memory
- [x] How to control lazy allocation and memory protection for the `Mapping`
- [ ] There should probably be a way to copy/CoW `Mapping`s, including between different address spaces
- [x] What should the signaute of `resize` be? (https://github.com/popcorn-2/popcorn-2/issues/24#issuecomment-1887352613)
    - Is it too surprising to change the base `Page` without returning a new object?

### Blockers
- `OwnedPages` is currently unstable, but used in the signature of the `raw_parts` methods (no tracking issue)
- `OwnedFrames` is currently marked as `kernel_internals`, but used in the signature of the `raw_parts` methods
- Virtual allocator design will likely change as part of #43 
- Protection API not finalised
- Physical allocator API not finalised

See https://github.com/popcorn-2/popcorn-2/issues/24#issuecomment-2217440037

**Comment by egkoppel** [comment]
At a minimum, any protection flag API should probably support:
- Unmapped but reserved by vmem allocator
- Read only
- Read & write
- Read & execute
- Read, write & execute

It would probably also be worth having control over cache attributes since this will be used for allocating DMA buffers, MMIO access, etc.

**Comment by egkoppel** [comment]
Added a `resize_in_place` to support things like heap allocation where existing pointers must not be invalidated. Should it be legal to grow downwards with `in_place` as this wouldn't invalidate existing pointers?

Since `remap` doesn't return anything on success, and requires a mutable reference, it is likely clear from the signature that the base can be modified.

**Comment by egkoppel** [comment]
At some point once the page table APIs are properly implemented (#16), virtual allocators and corresponding page tables will likely be combined into a single type, preventing any issues from allocating memory for the wrong address space.

**Comment by egkoppel** [comment]
Try and stabilise a subset of the commonly used parts of the API, avoiding the current blockers. This would probably include:
- `RawMapping`
    - `new()`
    - `resize_in_place()` - used by heap implementations
- `Config`
    - `new()`
    - `physical_location()` - used by MMIO
- `Location`
    - `Any`
    - `At` - used by MMIO
- `Stack`
- `Mapping`
