### ISSUE TITLE
List of nightly features required

### ISSUE THREAD

**Issue by egkoppel** [egkoppel/popcorn-2#74]
# bitmap_allocator

None

# bootloader

- [ ] `ptr_metadata` - rust-lang/rust#81513
- [ ] `try_blocks` - rust-lang/rust#31436
- [ ] `let_chains` - rust-lang/rust#53667
- [ ] `pointer_is_aligned_to` - rust-lang/rust#96284
- [ ] `new_uninit` - rust-lang/rust#63291
- [ ] `split_array` - rust-lang/rust#90091
- [x] `slice_ptr_len` - rust-lang/rust#71146
- [ ] `slice_ptr_get` - rust-lang/rust#74265
- [ ] `inline_const` - rust-lang/rust#76001
- [ ] `arbitrary_self_types` - rust-lang/rust#44874
- [ ] `concat_bytes` - rust-lang/rust#87555
- [ ] `allocator_api` - https://github.com/rust-lang/wg-allocators
- [ ] `iter_collect_into` - rust-lang/rust#94780
- [ ] `noop_waker` - rust-lang/rust#98286

# builder

- [ ] `decl_macro` -  rust-lang/rust#39412

# elf

- [ ] `pointer_is_aligned_to` -  rust-lang/rust#96284
- [x] `pointer_byte_offsets` -  rust-lang/rust#96283
- [ ] `never_type` -  rust-lang/rust#35121

# kernel

- [ ]
